source/vodpoints/Controllers/EdgeServerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using vodpoints.edmx;

namespace vodpoints.Controllers
{
    public class EdgeServerController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            var edgeservers = this.vodpointsdb.edgeservers.ToList();
            return View(edgeservers);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(edgeserver edgeserver)
        {
            if (ModelState.IsValid)
            {
                this.vodpointsdb.edgeservers.Add(edgeserver);
                this.vodpointsdb.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = this.vodpointsdb.edgeservers.Find(id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(edgeserver edgeserver)
        {
            if (ModelState.IsValid)
            {
                this.vodpointsdb.Entry(edgeserver).State = EntityState.Modified;
                this.vodpointsdb.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var edgeserver = this.vodpointsdb.edgeservers.Find(id);
            this.vodpointsdb.edgeservers.Remove(edgeserver);
            this.vodpointsdb.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

source/vodpoints/Views/EdgeServer/Create.cshtml
@model vodpoints.edmx.edgeserver
<div class="container-fluid">
    <!-- BEGIN PAGE CONTENT INNER -->
    <div class="portlet light">
        <!--標題-->
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-rss font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">
                    新增有線電視
                </span>
            </div>
        </div>
        <!--END 標題-->
        @using (Html.BeginForm("Create", "EdgeServer", FormMethod.Post))
        {
        @Html.ValidationSummary()
        <div class="portlet-body form">
            <form role="form">
                <div class="form-body">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">有線電視</label>
                            <div class="col-lg-2">
                                <input type="text" class="form-control" name="CableTVName">
                                @Html.ValidationMessageFor(a=> Model.CableTVName)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">Edge Server IP</label>
                            <div class="col-lg-2">
                                <input type="text" class="form-control IP" name="IP">
                                @Html.ValidationMessageFor(a=> Model.IP)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">登入帳號</label>
                            <div class="col-lg-3">
                                <input type="text" class="form-control" name="Account">
                                @Html.ValidationMessageFor(a=> Model.Account)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">登入密碼</label>
                            <div class="col-lg-2">
                                @Html.PasswordFor(a=>a.Password, new { @class = "form-control", placeholder="Password"})
                            </div>
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">密碼確認</label>
                            <div class="col-lg-2">
                                @Html.Password("ConfirmPassword", "", new { @class = "form-control"})
                                @Html.ValidationMessage("ConfirmPassword", "新舊密碼不符", new { @class = "small text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-offset-3 col-lg-9">
                                <button type="submit" class="btn btn-danger" id="EdgeServerCreate">儲存變更</button>
                                @Html.ActionLink("取消","Index","EdgeServer",null, new { @class="btn btn-primary"})
                            </div>
                        </div>
                    </div>
                </div>
            </form>


        </div>
        }
    </div>
    <!-- END PAGE CONTENT INNER -->
</div>

@section scripts{
    <script src="@Url.Content("~/Scripts/jquery.mask.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/EdgeServer.js")" type="text/javascript"></script>
}

source/vodpoints/Views/EdgeServer/Edit.cshtml
@model vodpoints.edmx.edgeserver

<div class="container-fluid">
    <!-- BEGIN PAGE CONTENT INNER -->
    <div class="portlet light">
        <!--標題-->
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-rss font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold uppercase">
                    修改頻道商
                </span>
            </div>
        </div>
        <!--END 標題-->
        @using (Html.BeginForm("Edit", "EdgeServer", FormMethod.Post))
        {
            @Html.ValidationSummary()
            <div class="portlet-body form">
            <form role="form">
                <div class="form-body">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">有線電視</label>
                            <div class="col-lg-2">
                                @Html.TextBoxFor(a=>a.CableTVName, new { @class="form-contrl"})
                                @Html.ValidationMessageFor(a=>a.CableTVName)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">Edge Server IP</label>
                            <div class="col-lg-2">
                                @Html.TextBoxFor(a=>a.IP, new { @class="form-contrl IP"})
                                @Html.ValidationMessageFor(a=>a.IP)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">登入帳號</label>
                            <div class="col-lg-2">
                                @Html.TextBoxFor(a=>a.Account, new { @class="form-contrl"})
                                @Html.ValidationMessageFor(a=>a.Account)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">密碼</label>
                            <div class="col-lg-2">
                                @Html.PasswordFor(a=>a.Password, new { @class="form-contrl", autocomplete = "off", placeholder="Password", value = Model.Password})
                                @Html.ValidationMessageFor(a=>a.Password)
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">密碼確認</label>
                            <div class="col-lg-2">
                                @Html.PasswordFor(a=>a.ConfirmPassword, new { @class="form-contrl", autocomplete = "off", placeholder="Password", value = Model.Password})
                                @Html.ValidationMessageFor(a => a.ConfirmPassword, "新舊密碼不符", new { @class = "small text-danger" })
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-offset-3 col-lg-9">
                                <button type="submit" class="btn btn-danger">儲存變更</button>
                                @Html.ActionLink("取消","Index","EdgeServer",null, new { @class="btn btn-primary"})
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        }
    </div>
    <!-- END PAGE CONTENT INNER -->
</div>

@section scripts{
    <script src="@Url.Content("~/Scripts/jquery.mask.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/EdgeServer.js")" type="text/javascript"></script>
}