source/vodpoints/Controllers/AuthorityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vodpoints.edmx;
using vodpoints.Models;

namespace vodpoints.Controllers
{
	public class AuthorityController : BaseController
	{
		[HttpGet]
		public ActionResult Index()
		{
			var models = this.vodpointsdb.authoritygroups.ToList();
			var dicAuthorityGroupUsers = new Dictionary<int, int>();
			foreach (var authorityGroup in models)
			{
				var countUsersInGroup = this.vodpointsdb.managerauthoritygroups.Where(a => a.AuthorityGroupId == authorityGroup.Id).Count();
				dicAuthorityGroupUsers.Add((int)authorityGroup.Id, countUsersInGroup);
			}

			ViewBag.DicAuthorityGroupUsers = dicAuthorityGroupUsers;
			return View(models);
		}

		[HttpGet]
		public ActionResult Delete(int id)
		{
			var authoritygroup = this.vodpointsdb.authoritygroups.Find(id);
			this.vodpointsdb.authoritygroups.Remove(authoritygroup);
			var managerAuthorityGroups = this.vodpointsdb.managerauthoritygroups.Where(a => a.AuthorityGroupId == id);
			this.vodpointsdb.managerauthoritygroups.RemoveRange(managerAuthorityGroups);
			this.vodpointsdb.SaveChanges();

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Create()
		{
			var managers = this.vodpointsdb.managers.ToList();
			var accesscontrolparents = this.vodpointsdb.accesscontrolparents.ToList();
			var accesscontrolchildren = this.vodpointsdb.accesscontrolchildrens.ToList();
			var model = new CompositeAuthorityViewModel();
			model.Managers = managers;
			model.AccessControlParent = accesscontrolparents;
			model.AccessControlChildren = accesscontrolchildren;
			return View(model);
		}

		[HttpPost]
		public ActionResult Create([Bind(Prefix = "authoritygroup")]authoritygroup authoritygroup, string[] managers, FormCollection collection)
		{
			using (var transaction = this.vodpointsdb.Database.BeginTransaction())
			{
				//// create new authoritygroup
				this.vodpointsdb.authoritygroups.Add(authoritygroup);
				this.vodpointsdb.SaveChanges();
				this.vodpointsdb.Entry(authoritygroup).GetDatabaseValues();
				var authorityGroupId = authoritygroup.Id;

				//// create data in managerauthoritygroup table
				foreach (var manager in managers)
				{
					var model = new managerauthoritygroup();
					model.AuthorityGroupId = authorityGroupId;
					model.ManagerId = this.vodpointsdb.managers.Where(a => a.Name == manager).First().Id;
					bool isExisted = this.vodpointsdb.managerauthoritygroups.Where(a => a.AuthorityGroupId == model.AuthorityGroupId && a.ManagerId == model.ManagerId).Any();

					if (!isExisted)
					{
						this.vodpointsdb.managerauthoritygroups.Add(model);
					}
				}

				//// create data in manageraccesscontrolchildren table
				foreach (var key in collection.AllKeys)
				{
					var accesscontrolchildrenId = 0;
					if (int.TryParse(key, out accesscontrolchildrenId) && collection[key] == "True")
					{
						foreach (var manager in managers)
						{
							var managerId = this.vodpointsdb.managers.Where(a => a.Name == manager).First().Id;
							bool isExisted = this.vodpointsdb.manageraccesscontrolchildrens.Where(a => a.AccessControlChildrenId == accesscontrolchildrenId && a.ManagerId == managerId).Any();

							if (!isExisted)
							{
								this.vodpointsdb.manageraccesscontrolchildrens.Add(new manageraccesscontrolchildren
								{
									AccessControlChildrenId = accesscontrolchildrenId,
									Function = 1,
									ManagerId = managerId
								});
							}
						}
					}
				}

				this.vodpointsdb.SaveChanges();
				transaction.Commit();
			}

			return RedirectToAction("Index");
		}
	}
}

source/vodpoints/Views/Authority/Create.cshtml
@model vodpoints.Models.CompositeAuthorityViewModel
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container-fluid">
        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="portlet light">
            <!--標題-->
            <div class="portlet-title">
                <h3 class="form-section"><i class="icon-user"></i>權限控管</h3>
            </div>
            <!--END 標題-->
@using (Html.BeginForm("Create", "Authority", FormMethod.Post))
{
            <div class="portlet-body form">
                <div class="form-body">
                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">群組名稱</label>
                            <div class="col-lg-2">
                                <input type="text" class="form-control" name="authoritygroup.Name" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">群組描述</label>
                            <div class="col-lg-2">
                                <input type="text" class="form-control" name="authoritygroup.Description" />
                            </div>
                        </div>
                    </div>

                    <h3 class="form-section">管理員選擇</h3>

                    <div class="form-group">
                        <div class="row">
                            <label class="col-lg-offset-1 col-lg-2 control-label">管理員</label>
                            <div class="col-lg-2">
                                @foreach (var item in Model.Managers)
                                {
                                    <input type="checkbox" name="Managers" value="@item.Name">@item.Name
                                }
                            </div>
                        </div>
                    </div>

                    <h3 class="form-section">權限</h3>

                    <div class="row">
                        <div class="col-md-1">&nbsp;</div>
                        <div class="col-md-8">
                            <div class="form-group">
                                <table class="table table-condensed" style="border-bottom-width: 2px; border-bottom: 1px inset #dddddd;">
                                    <thead>
                                        <tr>
                                            <th>群組</th>
                                            <th>項目</th>
                                            <th>完全控制</th>
                                            <th>禁止使用</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach (var parent in Model.AccessControlParent)
                                    {                                       
                                        <tr>
                                            <td rowspan="@Model.AccessControlChildren.Where(a=>a.ParentId == parent.Id).Count()" class="text-primary text-center">
                                                <i class="fa fa-film fa-3x"></i>
                                                <br />
                                                @parent.Name
                                            </td>
                                            <td>@Model.AccessControlChildren.Where(a=>a.ParentId == parent.Id).First().Name</td>
                                            <td>
                                                <input data-val="true" data-val-required="mam_upload 欄位是必要項。" id="mam_upload" name="@Model.AccessControlChildren.Where(a=>a.ParentId == parent.Id).First().Id" type="radio" value="True" />
                                            </td>
                                            <td>
                                                <input checked="checked" id="mam_upload" name="@Model.AccessControlChildren.Where(a=>a.ParentId == parent.Id).First().Id" type="radio" value="False" />
                                            </td>
                                        </tr>
                                        foreach(var children in Model.AccessControlChildren.Where(a=>a.ParentId == parent.Id).Skip(1))
                                        {
                                            <tr>
                                                <td>@children.Name</td>
                                                <td>
                                                    <input data-val="true" data-val-required="mam_download 欄位是必要項。" id="mam_download" name="@children.Id" type="radio" value="True" />
                                                </td>
                                                <td>
                                                    <input checked="checked" id="mam_download" name="@children.Id" type="radio" value="False" />
                                                </td>
                                            </tr>
                                        }
                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-offset-3 col-lg-9">
                                <button type="submit" class="btn btn-danger" id="AuthorityCreate">儲存變更</button>
                            </div>
                        </div>
                    </div>
                </div> 
            </div>
}
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>
</div>
<!-- END PAGE CONTENT -->

source/vodpoints/Views/Authority/Index.cshtml
@model List<vodpoints.edmx.authoritygroup>
@{
    var dicAuthorityGroupUsers = ViewBag.DicAuthorityGroupUsers as Dictionary<int, int>;
}
<!-- BEGIN PAGE CONTENT -->
<div class="page-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="portlet light">
                    <!--標題-->
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-user font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">
                                權限控管
                            </span>
                        </div>

                        <div class="actions">
                            <div class="btn-group">
                                <a class="btn btn-primary" href='@Url.Action("Create", "Authority")'>
                                    <i class="fa fa-plus-square"></i>&nbsp;新增控管群組
                                </a>
                            </div>
                        </div>
                    </div>
                    <!--END 標題-->
                    <!--內容-->
                    <div class="portlet-body">
                        <div class="table-scrollable">
                            <table class="table table-striped table-bordered table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th>
                                            <i class="fa fa-users"></i> 權限群組
                                        </th>
                                        <th class="hidden-xs">
                                            <i class="fa fa-user"></i> 套用此權限管理者
                                        </th>
                                        <th>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var authorityGroup in Model)
                                    {
                                    <tr>
                                        <td class="highlight">
                                            <div class="success">
                                            </div>
                                            <a href="javascript:;">
                                                @authorityGroup.Name
                                            </a>
                                        </td>
                                        <td class="hidden-xs">
                                            @dicAuthorityGroupUsers[(int)@authorityGroup.Id]
                                        </td>
                                        <td>
                                            <a href='@Url.Action("Delete", "Authority", new { id = @authorityGroup.Id })' class="btn default btn-xs purple">
                                                <i class="fa fa-trash-o"></i> 刪除
                                            </a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <!--END內容-->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END PAGE CONTENT -->
<!-- BEGIN PAGE CONTENT INNER -->
<!-- END PAGE CONTENT INNER -->